// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdRXDNhCjlFd1Ezua9FJuSzkxGOlGNETI',
    appId: '1:152471877043:web:5987bdcee0323b01dcc7c6',
    messagingSenderId: '152471877043',
    projectId: 'most-app-48373',
    authDomain: 'most-app-48373.firebaseapp.com',
    storageBucket: 'most-app-48373.firebasestorage.app',
    measurementId: 'G-GVH0FC2153',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa0SXFemOBLK8jSo0I0gjTEGx0hvnl3Xc',
    appId: '1:152471877043:android:e192f62df7824856dcc7c6',
    messagingSenderId: '152471877043',
    projectId: 'most-app-48373',
    storageBucket: 'most-app-48373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzDhOqrHv3kIpeTccsy0_HgrjqoimuIKA',
    appId: '1:152471877043:ios:fd3fe95934380c2bdcc7c6',
    messagingSenderId: '152471877043',
    projectId: 'most-app-48373',
    storageBucket: 'most-app-48373.firebasestorage.app',
    iosBundleId: 'com.example.mostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzDhOqrHv3kIpeTccsy0_HgrjqoimuIKA',
    appId: '1:152471877043:ios:fd3fe95934380c2bdcc7c6',
    messagingSenderId: '152471877043',
    projectId: 'most-app-48373',
    storageBucket: 'most-app-48373.firebasestorage.app',
    iosBundleId: 'com.example.mostApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdRXDNhCjlFd1Ezua9FJuSzkxGOlGNETI',
    appId: '1:152471877043:web:34cc7288c9aef260dcc7c6',
    messagingSenderId: '152471877043',
    projectId: 'most-app-48373',
    authDomain: 'most-app-48373.firebaseapp.com',
    storageBucket: 'most-app-48373.firebasestorage.app',
    measurementId: 'G-2Q12D787NM',
  );
}
